# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.16.1'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@11.1.2
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CopyFiles@2
  displayName: 'Copy dist to artifacts'
  inputs:
      SourceFolder: 'src/dist'
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)/dist'
      cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'angular-web-app'
    publishLocation: 'Container'